import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/common.css";
import "./styles/mg_pd.css";
import "./styles/flex.css";
import "./styles/font.css";
import Header from "@/app/components/Header/header";
import ReduxProvider from "../../store/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <ReduxProvider>
      <body>
        <Header/>
        {children}
      </body>
    </ReduxProvider>
    </html>
  );
}
